### ISSUE TITLE
Home - Searching bar

### ISSUE THREAD

**Issue by alegnaaived** [PEM-Humboldt/mibloque#9]
### Description:
Using a react component and states, implementing the searcher bar to select a sedimentary basin and sending it to the summary component.

### Acceptance criteria:
- [x] Show searching bar component
- [x] Allow writing in searching bar
- [x] Load dynamic data searched with the text in the searching bar
- [x] Saving selected sedimentary basin and sending it to the summary component

**Comment by erikasv** [comment]
Only to note that the search bar is for anh areas nor for sedimentry basins
